### ISSUE TITLE
`config.toml` file is present in the root directory

### ISSUE THREAD

**Issue by mircea-pavel-anton** [nunocoracao/blowfish_lowkey#1]
In the docs you mentioned that we should remove the `config.toml` file from the root of the directory and use the `config/_default/*.toml` files, but in this template there is a `config.toml` file both in the root and in the dedicated config directory.

**Comment by nunocoracao** [comment]
Thanks for pointing this out @mirceanton I've removed the files across all projects. In previous versions of Hugo this was an issue, apparently, now it isn't. Not sure if something changed there.
